"""followers

Revision ID: 8493ce257560
Revises: c44b69e1e4e8
Create Date: 2023-11-11 10:50:09.186484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8493ce257560'
down_revision = 'c44b69e1e4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
